### ISSUE TITLE
Author missing in PDF info/XMP metadata when building with hyperxmp 5.11

### ISSUE THREAD

**Issue by michaelroland** [michaelroland/jku-templates-report-latex#16]
The author field is no longer filled in PDF info/XMP metadata when building with hyperxmp 5.11 on texlive:latest. The author filed is properly used when compiling with MikTeX and hyperxmp 5.9.

This need further debugging.

**Comment by michaelroland** [comment]
- Log output for TeXlive: [main-thesis-xelatex-texlive.log](https://github.com/michaelroland/jku-templates-report-latex/files/12232322/main-thesis-xelatex-texlive.log)
- Log output for MikTeX: [main-thesis-xelatex-miktex.log](https://github.com/michaelroland/jku-templates-report-latex/files/12232323/main-thesis-xelatex-miktex.log)

**Comment by kmccurley** [comment]
I can confirm that I have also observed this in hyperxmp 5.11.

**Comment by michaelroland** [comment]
Solved by #17 Thx @CrazyChaoz
