### ISSUE TITLE
ISO date not parsed (but left as-is) for non-thesis type documents

### ISSUE THREAD

**Issue by ernstleierzopf** [michaelroland/jku-templates-report-latex#18]
use DTMdisplaydate as temporary solution within the date command:
`\date{\DTMdisplaydate{YYYY}{MM}{DD}{-1}}`

**Comment by michaelroland** [comment]
This is actually a bug in the current documentation of [main-report.tex](https://github.com/michaelroland/jku-templates-report-latex/blob/v2.1/main-report.tex). I had intended to actually use whatever date verbatim. Parsing was only meant for the thesis version where we need a very specific format (Month YYYY) on the title page. However, it would actually be nice to detect if a date in ISO format (YYYY-MM-DD) is given and parse that as a real date to print it in the current language-specific format.
