### ISSUE TITLE
Increase line spacing to improve readability

### ISSUE THREAD

**Issue by p-hofer** [michaelroland/jku-templates-report-latex#23]
Current layout seems to set line spacing to 1.0, which makes the text hard to read.

**Comment by michaelroland** [comment]
While the line spacing is already 1.2x the font size, I agree that this is rather dense (particularly with the Merriweather font). I'll set the linespread to 1.1 to give some extra spacing.

**Comment by michaelroland** [comment]
Resolved by 77e242880dab766d1b963b25ea35febb5151e6b8
